name       : python-rencode
version    : 1.0.6
release    : 1
source     :
    - https://github.com/aresch/rencode/archive/v1.0.6.tar.gz : 0ed61111f053ea37511da86ca7aed2a3cfda6bdaa1f54a237c4b86eea52f0733
license    : GPL-3.0-or-later
component  : programming.python
summary    : Python module for fast object serialization
description: |
     Python module for fast (basic) object serialization similar to bencode.
     This version of rencode is a complete rewrite in Cython to attempt to increase the performance over the pure Python module written by Petru Paler, Connelly Barnes et al.
builddeps  :
    - cython
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
